# Generated by Django 5.2.7 on 2025-11-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reputation_score',
            field=models.IntegerField(default=0),
        ),
    ]
