# Generated by Django 5.2.7 on 2025-11-02 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Descrição do problema (suporta Markdown)')),
                ('is_published', models.BooleanField(default=False)),
                ('is_solutioned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(related_name='question_likes', to='profiles.userprofile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='profiles.userprofile')),
                ('tecnologies', models.ManyToManyField(related_name='question_tags', to='technologies.technology')),
            ],
        ),
    ]
