# Generated by Django 5.2.7 on 2025-11-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_is_published_alter_question_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tecnologies',
            new_name='technologies',
        ),
    ]
