# Generated by Django 5.2.7 on 2025-11-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_reputation_score'),
        ('questions', '0003_rename_tecnologies_question_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(related_name='question_likes', to='profiles.userprofile'),
        ),
    ]
