# Generated by Django 5.2.7 on 2025-11-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_alter_answer_upvotes'),
        ('profiles', '0002_alter_userprofile_reputation_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvote', to='profiles.userprofile'),
        ),
    ]
