# Generated by Django 5.2.7 on 2025-11-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('profiles', '0002_alter_userprofile_reputation_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='article_likes', to='profiles.userprofile'),
        ),
    ]
