# Generated by Django 5.2.7 on 2025-11-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_is_published_alter_article_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tecnologies',
            new_name='technologies',
        ),
    ]
