# Generated by Django 5.2.7 on 2025-11-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_tecnologies_article_technologies'),
        ('profiles', '0002_alter_userprofile_reputation_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(related_name='article_likes', to='profiles.userprofile'),
        ),
    ]
