# Generated by Django 5.2.7 on 2025-11-02 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=80)),
                ('type_credential', models.CharField(choices=[('PRO', 'Profissional'), ('GRA', 'Graduado')])),
                ('experience', models.CharField(choices=[('JR', 'Júnior'), ('PL', 'Pleno'), ('SR', 'Sênior')])),
                ('institution', models.CharField(max_length=120)),
                ('start_date', models.DateField(help_text='Data de início')),
                ('end_date', models.DateField(blank=True, help_text='Data de término (deixe em branco se for atual)', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text="Marque como 'True' se esta credencial foi validada pelo admin")),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
            options={
                'unique_together': {('profile', 'role', 'institution')},
            },
        ),
    ]
