# Generated by Django 5.2.7 on 2025-11-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#5e6e7d', help_text="Cor do 'badge' (Hex). Sempre usado se não houver logo.", max_length=7)),
                ('logo', models.ImageField(blank=True, help_text='Logo da tecnologia (opcional).', null=True, upload_to='tech_logos/')),
                ('prism_lang', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'unique_together': {('name', 'slug', 'logo')},
            },
        ),
    ]
